name: hh_catcher
services:
    hh_parser:
        container_name: hh_parser
        build: .
        environment:
            HH_LOGIN_FILE: /run/secrets/hh_login
            HH_PASSWORD_FILE: /run/secrets/hh_password
        secrets:
          - hh_login
          - hh_password

secrets:
  hh_login:
    file: hh_login.txt
  hh_password:
    file: hh_password.txt
