name: hh_catcher
services:
    hh_parser:
        container_name: hh_parser
        build: .
        environment:
            HH_LOGIN_FILE: /run/secrets/hh_login
            HH_PASSWORD_FILE: /run/secrets/hh_password
            POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
        volumes:
          - type: bind
            source: csv_vault
            target: /csv_vault
        secrets:
          - hh_login
          - hh_password
          - pg_password
        depends_on:
          pg_db:
            condition: service_healthy

    pg_db:
        container_name: pg_db
        image: postgres:alpine
        restart: always
        environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD_FILE=run/secrets/pg_password
          - POSTGRES_DB=hh_results
        secrets:
          - pg_password
        ports:
          - 5432:5432
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U admin -d hh_results" ]
            interval: 10s
            timeout: 5s
            retries: 5
#        volumes:
#          - type: volume
#            source: pg_data
#            target: /var/lib/postgresql/data

secrets:
  hh_login:
    file: hh_login.txt
  hh_password:
    file: hh_password.txt
  pg_password:
    file: pg_password.txt

volumes:
  csv_vault:
#  pg_data:
