name: hh_catcher
services:
    hh_parser:
        container_name: hh_parser
        build: .
        environment:
            HH_LOGIN_FILE: /run/secrets/hh_login
            HH_PASSWORD_FILE: /run/secrets/hh_password
        volumes:
          - type: bind
            source: csv_vault
            target: /csv_vault
        secrets:
          - hh_login
          - hh_password
        depends_on:
          pg_db:
            condition: service_healthy

    pg_db:
        container_name: pg_db
        image: postgres:alpine
        restart: always
        environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=test123
          - POSTGRES_DB=hh_results
        ports:
          - 5432:5432
        volumes:
          - type: volume
            source: pg_data
            target: /var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U admin -d hh_results" ]
            interval: 30s
            timeout: 10s
            retries: 5

secrets:
  hh_login:
    file: hh_login.txt
  hh_password:
    file: hh_password.txt

volumes:
  csv_vault:
  pg_data:
